
version: 2

models:
  - name: stg_order_mod_tbl
    columns:
      - name: order_id
        description: "The order_id not null"
        tests:
          - not_null
          - unique
      - name: order_status
        tests:
          - not_null
          - accepted_values:
             values:
              - Cancelled
              - Out for delivery

